#!/usr/bin/env python3
"""Rebuild assets/data/rep-visits.js from the Outlook rep-visits calendar.

The calendar URL is read ONLY from the OUTLOOK_ICS_URL environment variable
(a GitHub Actions secret). It is never written to any file or printed.
Uses only the Python standard library.
"""
import json, os, re, sys, urllib.request
from datetime import datetime, date, timedelta, timezone
from zoneinfo import ZoneInfo

TZ = ZoneInfo("America/New_York")
OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "data", "rep-visits.js")
DAYS_AHEAD = 90

url = os.environ.get("OUTLOOK_ICS_URL", "").strip()
if not url:
    sys.exit("OUTLOOK_ICS_URL secret is not set; leaving rep-visits.js unchanged.")

try:
    raw = urllib.request.urlopen(url, timeout=60).read().decode("utf-8", "replace")
except Exception as ex:
    sys.exit("Could not download the calendar (%s); leaving rep-visits.js unchanged." % type(ex).__name__)

if "BEGIN:VCALENDAR" not in raw:
    sys.exit("Download was not a calendar; leaving rep-visits.js unchanged.")

# Unfold continuation lines, then collect VEVENT properties.
lines = re.sub(r"\r?\n[ \t]", "", raw).splitlines()
events, cur = [], None
for ln in lines:
    if ln == "BEGIN:VEVENT":
        cur = {}
    elif ln == "END:VEVENT":
        if cur is not None:
            events.append(cur)
        cur = None
    elif cur is not None and ":" in ln:
        key, val = ln.split(":", 1)
        parts = key.split(";")
        cur[parts[0].upper()] = (val, dict(p.split("=", 1) for p in parts[1:] if "=" in p))

def parse_dt(prop):
    val, params = prop
    if params.get("VALUE") == "DATE" or re.fullmatch(r"\d{8}", val):
        return datetime.strptime(val, "%Y%m%d"), True
    if val.endswith("Z"):
        return datetime.strptime(val, "%Y%m%dT%H%M%SZ").replace(tzinfo=timezone.utc).astimezone(TZ), False
    dt = datetime.strptime(val, "%Y%m%dT%H%M%S")
    tz = params.get("TZID", "")
    try:
        zone = ZoneInfo(tz)
    except Exception:  # Outlook uses Windows names like "Eastern Standard Time"
        zone = TZ
    return dt.replace(tzinfo=zone).astimezone(TZ), False

def fmt(dt):
    return dt.strftime("%I:%M %p").lstrip("0")

def unescape(t):
    return t.replace("\\n", " ").replace("\\,", ",").replace("\\;", ";").replace("\\\\", "\\").strip()

today = date.today()
last = today + timedelta(days=DAYS_AHEAD)
rows = []
for ev in events:
    if "DTSTART" not in ev or "SUMMARY" not in ev:
        continue
    if ev.get("STATUS", ("",))[0].upper() == "CANCELLED":
        continue
    start, allday = parse_dt(ev["DTSTART"])
    if "RRULE" in ev:
        print("Skipping recurring event (not supported):", ev["SUMMARY"][0], file=sys.stderr)
        continue
    d = start.date()
    if d < today or d > last:
        continue
    name = unescape(ev["SUMMARY"][0])
    time = ""
    if not allday:
        time = fmt(start)
        if "DTEND" in ev:
            end, _ = parse_dt(ev["DTEND"])
            if end > start:
                time += " – " + fmt(end)
    rows.append({"date": d.isoformat(), "name": name, "time": time, "_s": start.isoformat()})

rows.sort(key=lambda r: r["_s"])
for r in rows:
    del r["_s"]

body = ("// AUTO-GENERATED by scripts/update-rep-visits.py from the rep-visits calendar.\n"
        "// Do not edit by hand; changes are overwritten each week.\n"
        "const REP_VISITS = [\n" + ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in rows) + "\n];\n")
with open(OUT, "w", encoding="utf-8") as f:
    f.write(body)
print("Wrote %d rep visits." % len(rows))
